# Archivo de configuración para DigitalOcean App Platform
name: monifly-backend
services:
- name: api
  source_dir: /
  github:
    repo: JuanGilles123/monifly-backend
    branch: main
  build_command: |
    composer install --no-dev --prefer-dist --optimize-autoloader \
    && php artisan optimize:clear \
    && (npm ci --no-audit --no-fund || npm install --no-audit --no-fund) \
    && npm run build
  run_command: heroku-php-apache2 public/
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  buildpacks:
  - heroku/php
  - heroku/nodejs
  envs:
  - key: APP_NAME
    value: MoniFly
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: https://monifly.app
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ${monifly-db.HOSTNAME}
  - key: DB_PORT
    value: ${monifly-db.PORT}
  - key: DB_DATABASE
    value: ${monifly-db.DATABASE}
  - key: DB_USERNAME
    value: ${monifly-db.USERNAME}
  - key: DB_PASSWORD
    value: ${monifly-db.PASSWORD}
  - key: SESSION_DRIVER
    value: cookie
  - key: CACHE_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: database
databases:
- engine: PG
  name: monifly-db
  num_nodes: 1
  size: basic-xs
