# Archivo de configuración para DigitalOcean App Platform
name: monifly-backend
services:
- name: api
  source_dir: /
  github:
    repo: JuanGilles123/monifly-backend
    branch: main
  run_command: |
    php artisan migrate --force
    php artisan serve --host=0.0.0.0 --port=$PORT
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: APP_NAME
    value: MoniFly
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: https://monifly.app
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: SESSION_DRIVER
    value: cookie
  - key: CACHE_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: database
databases:
- engine: PG
  name: monifly-db
  num_nodes: 1
  size: basic-xs
